version: '3.4'

services:
  catalogdb:
    image: mongo
  webapi.mongodb:
    image: ${DOCKER_REGISTRY-}webapimongodb
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    hostname: "sqlserver"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Z0AmMM#8j2!o"
    #volumes:
    #  - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - "11433:1433"    
    expose:
      - 1433
volumes:
  mongo_data:
